### PR TITLE
Adjust and clean-up authorization tests for Python

### PR DESCRIPTION
**Pull request by robsdedude**

### CODE REVIEW

**Comment by injectives** [comment]
This WIP looks promising 👍
I felt like we needed some form of callback in between TX function retries, but I would surface this API for TX functions until we see valid use-cases in other areas. In my view, it would also be nice to register hooks through some methods instead of adding things to maps, but this is just my subjective view.

**Comment by injectives** [comment]
Given that it is possible to detect when first attempt happens, would it be possible to use 1 stub server for TX function tests? (I haven't tried this)

**Comment by robsdedude** [comment]
> Given that it is possible to detect when first attempt happens, would it be possible to use 1 stub server for TX function tests? (I haven't tried this)

Yes, it probably is, and this should be preferable because it doesn't require the driver to support routing :+1:

**Comment by robsdedude** [comment]
> > Given that it is possible to detect when first attempt happens, would it be possible to use 1 stub server for TX function tests? (I haven't tried this)
> 
> Yes, it probably is, and this should be preferable because it doesn't require the driver to support routing

But at the same time I'd like to leave this work for another PR as I want this to be merged before doing the Python driver beta release

**Review by injectives — APPROVED** [review]
LGTM

**Pull request merged**
