### PR TITLE
Make rollback optional when dealing with unknown time zones

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Review by robsdedude — APPROVED** [review]
:goal_net:

**Comment by fbiville** [comment]
JavaScript fails for unrelated reasons.
Java seems to fail because of the change (it counts 0 rollbacks). That's super weird, because it should have failed before this PR if no rollback occurs and the build passes on the 5.0 branch 🤔

**Comment by fbiville** [comment]
Java is now fixed: https://github.com/neo4j/neo4j-java-driver/pull/1269
Let's try again 🙏

**Comment by fbiville** [comment]
Seems the Java failures are flaky and unrelated to this PR. Merging this now.

**Pull request merged**
