### PR TITLE
Added ruby backend

### PR DESCRIPTION
**Pull request by klobuczek**

### CODE REVIEW

**Comment by bigmontz** [comment]
Hi @klobuczek, thanks for your contribution. 

Your PR looks good, but I think It could be a good idea to move the content of folder `driver/ruby/` to a folder called `testkit` in the driver repository as you could see [javascript driver](https://github.com/neo4j/neo4j-javascript-driver) for example. It allows you update some details in you build process without have to open a PR to testkit.

**Comment by klobuczek** [comment]
@bigmontz I was looking for that, but could not figure how that works. Does the directory have to be called `testkit` under the driver? Will testkit first look at that location before using its own language-specific directory? Does it work on 4.2 branch or only 4.3?

**Comment by fbiville** [comment]
@klobuczek thanks for your contribution. The team has agreed to merge it. 🥳 

As you already know, the end goal is to make `testkit` a testing utility that will support external driver (author)s. There are a few planned improvements down the road. These include documentation, some form of backwards compatibility and more.

For the time being, however, there is no guarantee about all these things.
We're happy to help you in a best effort fashion, but you should expect a few breaking changes for a while until the project stabilizes.

**Comment by klobuczek** [comment]
Thanks. It would be still great to know how to do it on the driver side. Because I would like to include testkit as part of the ruby driver github actions CI.

**Comment by robsdedude** [comment]
Yes, you'd have to add a folder named `testkit` into the driver's repository. This folder will be prioritized over a folder in testkit's own repo. You can find examples of this in the official driver's code. I'd recommend looking at the [go driver](https://github.com/neo4j/neo4j-go-driver/tree/4.3). There's a folder `testkit` with python scripts that configure how testkit calls the driver's backend and a folder `testkit-backend` (could be named differently) that contains the actual backend code in the driver's language. But as @fbiville said: this is all still unstable.

**Pull request merged**
