### PR TITLE
Do not skip ROUTE with bookmarks tests for Go driver anymore

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
~Currently opened as draft, as long as https://github.com/neo4j/neo4j-go-driver/pull/209 is not merged.~
EDIT: Driver PR now merged

**Comment by fbiville** [comment]
I can update the PR to remove all test skips since all drivers support ROUTE+bookmarks now.

**Comment by fbiville** [comment]
... well, I tried 😅 
Shall I revert to the first commit since it passes CI? WDYT @robsdedude?

**Comment by robsdedude** [comment]
@fbiville I'd say yes. Until we have a way to tie driver versions to testkit commits, the main branches should stay green at all times.

**Pull request merged**
