### PR TITLE
Add xml reporting to test suites

### PR DESCRIPTION
**Pull request by bigmontz**
Co-authored-by: Florent Biville <florent.biville@neo4j.com>

### CODE REVIEW

**Comment by robsdedude** [comment]
Is there still a need for XML output?

**Comment by fbiville** [comment]
It _might_ make the output easier to digest by TeamCity since JUnit XML format is quite well supported in general.

**Comment by robsdedude** [comment]
I think https://github.com/neo4j-drivers/testkit/pull/553 might be good enough:tm:  for now? If you disagree, please resolve the conflicts. I'd like to see what the output looks like in TC.

Also, I'd like the XML runner only to be chose in TC builds. For local development I really don't want to have to juggle around XML. Plain text on my command promt is very much appreciated.

**Comment by fbiville** [comment]
Let's close this for now

**Pull request closed without merging**
