### PR TITLE
Add tests for Bolt fix for broken DateTime encoding

### PR DESCRIPTION
**Pull request by robsdedude**
TODO: 
 - [x] add/fix unit tests for stub server changes
 - [x] self-review
 - [x] clean up
 - [x] external review
 - [x] merge
 - [x] backport to TestKit 4.4 to test 4.4 drivers
       https://github.com/neo4j-drivers/testkit/pull/476
 - [x] adjust StubScript specific JOLT documentation

### CODE REVIEW

**Comment by injectives** [comment]
Just to note, some 4.4 routing tests seem to fail because `HELLO` includes `"patch_bolt": ["utc"]`.

**Comment by injectives** [comment]
[This](e859d9566934a3ddf7303e57ca9c4a93e2ee539e) version works with [Java driver](https://github.com/neo4j/neo4j-java-driver/pull/1247).

**Comment by injectives** [comment]
[This](e859d9566934a3ddf7303e57ca9c4a93e2ee539e) version works with Java driver https://github.com/neo4j/neo4j-java-driver/pull/1247.

**Comment by injectives** [comment]
This version works with Java driver https://github.com/neo4j/neo4j-java-driver/pull/1247.

**Review by injectives — APPROVED** [review]

**Review by bigmontz — APPROVED** [review]
🕥 🕦

**Pull request merged**
