### PR TITLE
Bump neo4j server versions

### PR DESCRIPTION
**Pull request by robsdedude**
Add 5.1, 5.5 and nightly 5.x to test matrix

### CODE REVIEW

**Comment by robsdedude** [comment]
One thing at a time.

Superseded by https://github.com/neo4j-drivers/testkit/pull/545 (only updating ITs, test matrix update later)

**Review by AndyHeap-NeoTech — APPROVED** [review]
LGTM

**Review by bigmontz — APPROVED** [review]
🥦

**Review by bigmontz — APPROVED** [review]
🐰

**Pull request merged**
